Repository learning-process/ppc-2025-threads, pull requests merged in 2025-02, with the labels that each got.

#2 Adjust repo links
  README.md
  docs/README.md
Labels: docs

#4 Remove OpenSSL
  .github/workflows/main.yml
Labels: ci

#5 Update func_all.cpp
  tasks/all/example/func_tests/func_all.cpp
Labels: task:all

#6 Update create_perf_table.py
  scripts/create_perf_table.py
Labels: infrastructure

#20 Print gtest output in run_perf_counter.py
  scripts/run_perf_counter.py
Labels: infrastructure

#30 Disable bugprone-easily-swappable-parameters in clang-tidy config
  .clang-tidy
Labels: infrastructure
